### ISSUE TITLE
Support wasm runtime as a realm

### ISSUE THREAD

**Issue by bitboom** [Samsung/islet#26]
## Task
- [x] Select a wasm runtime for realm el0
- [x] Select kernel for realm for realm el1
- [x] Compose wasm realm

## Conclusion
I made `realm-wasm` with `wamer` + `linux`, by embedding a wasmer into initrd.
This is the simplest way to make `realm-wasm` through statically built into rootfs for linux.

_The reason why i didn't choose `unikraft` + `wasm runtime` combo is that there is no combo fully supporting aarch64 without modification._

Below is a summary of data i investigated.

## Summary
| kernel | runtime | aarch64 | x86_64 | emulator | remarks |
|---|---|---|---|---|---|
| linux | wasmer | O | O | qemu-user-aarch64 | latest version supported (3.1.4) |
| linux | wasmtime | O | O | qemu-user-aarch64 | aarch64: stable-0.26.1 only supported |
| unikraft | wamr | X | O | n/a | |
| unikraft | rust | X | O | n/a | |
| unikraft | c | O | O | qemu-system-aarch64 | |
| nanos | c | O | O | qemu-system-aarch64 | |
| nanos | wasmer | X | O | qemu-system-aarch64 | |
| nanos | wasmedge | X | O | qemu-system-aarch64 | |
