### ISSUE TITLE
Manage the memory region state

### ISSUE THREAD

**Issue by isaac2-lee** [Samsung/islet#61]
### Granule structure
ref. tf-rmm

Granule state
```rust
pub enum GranuleState {
    Undelegated,
    Delegated,
    RD,
    Rec,
    RecAux,
    Data,
    RTT,
}
```

data structure
```
pub struct Granule {
    state: GranuleState,
    refcount: usize,
    idx: usize,
}
```

**Comment by isaac2-lee** [comment]
code : [link](https://github.com/Samsung/islet/commit/7d09a024ed78268bd4610f370befd977253278d1)

**Comment by isaac2-lee** [comment]
![image](https://user-images.githubusercontent.com/117252568/234769015-ef0ed6d2-fcf0-4b1d-8af2-cb3aed380ce1.png)

Memory mapping 고려하면,

DELEGATE 상태에서는 stage1 mmu에는 unmapping 상태(Granule에는 기록)
1. RD, REC state로 변경시 stage 1에 mapping
1. DELEGATE 상태로 변경되면 다시 unmapping으로 유지
1. UNDELEGATE 상태로 변경되면 Granule에서 삭제

**Comment by isaac2-lee** [comment]
### TO-DO
- [ ] reference count 가 필요한것인지 재확인
- [ ] tf-a-tests에서 Undelegated 상태에서 Delegate 조회하는 command는 fail 처리를 해야될까..
- [ ] RD, REC 사용처?에서 tf-a-tests에서는 delegated 상태로 놔두어도 (translation table에 추가 하지 않아도) 현재는 문제없는데... 재확인필요

**Comment by isaac2-lee** [comment]
### reference count 가 필요한것인지 재확인
specification에 따르면 reference count는 필요에 의해 tf-rmm이 자체 생성한것. 만들어야될 조건은 없음
단 pas는 존재해야함.

###  tf-a-tests에서 Undelegated 상태에서 Delegate 조회하는 command는 fail 처리를 해야될까..
ipa, ripas 구현이 완료되면 잘못된 state 조회는 panic 발생으로 전환
